/**
 * API 05 - Product Order & Stock Transfer Constants
 */

const PRODUCT_ORDER_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  PARTIALLY_APPROVED: "PARTIALLY_APPROVED",
  REJECTED: "REJECTED",
  DISPATCHED: "DISPATCHED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const STOCK_TRANSFER_STATUS = {
  PENDING: "PENDING",
  DISPATCHED: "DISPATCHED",
  RECEIVED: "RECEIVED",
  CANCELLED: "CANCELLED",
};

module.exports = {
  PRODUCT_ORDER_STATUS,
  STOCK_TRANSFER_STATUS,
};
