/**
 * Module 05 - Product Order & Stock Transfer Constants
 */

const ORDER_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  PARTIALLY_APPROVED: "PARTIALLY_APPROVED",
  REJECTED: "REJECTED",
  DISPATCHED: "DISPATCHED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
});

const TRANSFER_STATUS = Object.freeze({
  PENDING: "PENDING",
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  DISPATCHED: "DISPATCHED",
  RECEIVED: "RECEIVED",
  CANCELLED: "CANCELLED",
});

const PRODUCT_ORDER_STATUS = ORDER_STATUS;
const STOCK_TRANSFER_STATUS = TRANSFER_STATUS;

module.exports = {
  ORDER_STATUS,
  TRANSFER_STATUS,
  PRODUCT_ORDER_STATUS,
  STOCK_TRANSFER_STATUS,
};
