const mongoose = require("mongoose");

/**
 * Branch Mongoose Schema
 * Contains ONLY the required fields:
 * - _id (Native ObjectId auto-generated by MongoDB)
 * - name (Unique String)
 * - code (Unique String)
 * - address (String)
 * - branchType (String)
 * - weeklyOffDays (Array of Strings)
 * - createdAt (Date)
 * - updatedAt (Date)
 */
const branchSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Branch name is required"],
      unique: true,
      trim: true,
    },
    code: {
      type: String,
      required: [true, "Branch code is required"],
      unique: true,
      trim: true,
      uppercase: true,
    },
    address: {
      type: String,
      trim: true,
      default: "",
    },
    branchType: {
      type: String,
      trim: true,
      default: "retail",
    },
    weeklyOffDays: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
    versionKey: false,
    strict: true,
    toJSON: {
      virtuals: false,
      transform: (doc, ret) => {
        return {
          _id: ret._id,
          name: ret.name,
          code: ret.code,
          address: ret.address || "",
          branchType: ret.branchType || "retail",
          weeklyOffDays: ret.weeklyOffDays || [],
          createdAt: ret.createdAt,
          updatedAt: ret.updatedAt,
        };
      },
    },
  }
);

const Branch = mongoose.model("Branch", branchSchema, "branches");

module.exports = Branch;
