const mongoose = require("mongoose");

/**
 * PastDateRequest Mongoose Schema
 * Contains ONLY the required fields:
 * - _id (Native ObjectId auto-generated by MongoDB)
 * - branchId (Native ObjectId or null if appliesToAllBranches=true)
 * - appliesToAllBranches (Boolean)
 * - requestedBy (String, User ID or Name)
 * - requestedDate (String, e.g. "2025-09-01 09:00:00")
 * - requestedDateAt (ISODate)
 * - status (String, "Pending" | "Approved" | "Rejected")
 * - type (String, e.g. "Manual Admin Grant")
 * - createdAt (ISODate)
 * - updatedAt (ISODate or null)
 */
const pastDateRequestSchema = new mongoose.Schema(
  {
    branchId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Branch",
      default: null,
      index: true,
    },
    requestedBranch: {
      type: String,
      default: null,
      trim: true,
    },
    appliesToAllBranches: {
      type: Boolean,
      default: false,
    },
    requestedBy: {
      type: String,
      required: [true, "Requested by is required"],
      trim: true,
    },
    requestedByName: {
      type: String,
      default: null,
      trim: true,
    },
    requestedByEmail: {
      type: String,
      default: null,
      trim: true,
    },
    requestedByUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    requestedDate: {
      type: String,
      required: [true, "Requested date is required"],
      trim: true,
      index: true,
    },
    requestedDateAt: {
      type: Date,
      default: function () {
        return this.requestedDate ? new Date(this.requestedDate) : new Date();
      },
    },
    status: {
      type: String,
      enum: ["Pending", "Approved", "Rejected"],
      default: "Pending",
      index: true,
    },
    type: {
      type: String,
      default: "Manual Admin Grant",
      trim: true,
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
    updatedAt: {
      type: Date,
      default: null,
    },
  },
  {
    versionKey: false,
    strict: true,
    toJSON: {
      virtuals: false,
      transform: (doc, ret) => {
        return {
          _id: ret._id,
          branchId: ret.branchId || null,
          requestedBranch: ret.requestedBranch || null,
          branchName: ret.branchName || ret.requestedBranch || null,
          appliesToAllBranches: Boolean(ret.appliesToAllBranches),
          requestedBy: ret.requestedBy,
          requestedByName: ret.requestedByName || null,
          requestedByEmail: ret.requestedByEmail || null,
          requestedByUserId: ret.requestedByUserId || null,
          requestedDate: ret.requestedDate,
          requestedDateAt: ret.requestedDateAt,
          status: ret.status,
          type: ret.type,
          createdAt: ret.createdAt,
          updatedAt: ret.updatedAt || null,
        };
      },
    },
  }
);

pastDateRequestSchema.index({ branchId: 1, requestedDate: 1 });
pastDateRequestSchema.index({ status: 1, requestedDate: 1 });

const PastDateRequest = mongoose.model("PastDateRequest", pastDateRequestSchema, "pastDateRequests");

module.exports = PastDateRequest;
