const mongoose = require("mongoose");

/**
 * PaymentToBeCollected Mongoose Schema
 * Contains ONLY the required fields:
 * - _id (Native ObjectId auto-generated by MongoDB)
 * - branchId (Native ObjectId referencing Branch)
 * - date (String, format "YYYY-MM-DD")
 * - dateAt (ISODate)
 * - balance (Number)
 * - paymentCollectedTillNow (Number)
 * - paymentToBeCollected (Number)
 * - items (Array)
 * - createdAt (ISODate)
 * - updatedAt (ISODate)
 */
const paymentToBeCollectedSchema = new mongoose.Schema(
  {
    branchId: {
      type: mongoose.Schema.Types.Mixed,
      ref: "Branch",
      default: null,
      index: true,
    },
    branchName: {
      type: String,
      trim: true,
      index: true,
      default: null,
    },
    branch: {
      type: String,
      trim: true,
      default: null,
    },
    date: {
      type: String,
      required: [true, "Date is required"],
      trim: true,
      index: true,
    },
    dateAt: {
      type: Date,
      default: function () {
        return this.date ? new Date(this.date) : new Date();
      },
    },
    balance: {
      type: Number,
      default: 0,
    },
    paymentCollectedTillNow: {
      type: Number,
      default: 0,
    },
    paymentToBeCollected: {
      type: Number,
      default: 0,
    },
    items: {
      type: Array,
      default: [],
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
    updatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    versionKey: false,
    strict: true,
    toJSON: {
      virtuals: false,
      transform: (doc, ret) => {
        return {
          _id: ret._id,
          branchId: ret.branchId,
          branchName: ret.branchName || ret.branch || "",
          branch: ret.branch || ret.branchName || "",
          date: ret.date,
          dateAt: ret.dateAt,
          balance: typeof ret.balance === "number" ? ret.balance : 0,
          paymentCollectedTillNow: typeof ret.paymentCollectedTillNow === "number" ? ret.paymentCollectedTillNow : 0,
          paymentToBeCollected: typeof ret.paymentToBeCollected === "number" ? ret.paymentToBeCollected : 0,
          items: Array.isArray(ret.items) ? ret.items : [],
          createdAt: ret.createdAt,
          updatedAt: ret.updatedAt,
        };
      },
    },
  }
);

paymentToBeCollectedSchema.index({ branchId: 1, date: 1 });

const PaymentToBeCollected = mongoose.model(
  "PaymentToBeCollected",
  paymentToBeCollectedSchema,
  "paymentToBeCollected"
);

module.exports = PaymentToBeCollected;
