/**
 * API 09 - SLA Hierarchy & Designer Rating Constants
 */

const SLA_STAGES = {
  DESIGN_ACCEPTANCE: "DESIGN_ACCEPTANCE",
  DESIGN_START: "DESIGN_START",
  SAMPLE_SUBMISSION: "SAMPLE_SUBMISSION",
  REVISION_TURNAROUND: "REVISION_TURNAROUND",
  CUSTOMER_APPROVAL: "CUSTOMER_APPROVAL",
  DESIGN_COMPLETION: "DESIGN_COMPLETION",
  PRINTING: "PRINTING",
  FINISHING: "FINISHING",
  PACKING: "PACKING",
  QC: "QC",
  OVERALL: "OVERALL",
};

const SLA_STATUS = {
  WITHIN_SLA: "WITHIN_SLA",
  APPROACHING: "APPROACHING",
  BREACHED: "BREACHED",
  MET: "MET",
};

module.exports = {
  SLA_STAGES,
  SLA_STATUS,
};
