/**
 * API 02 - Common Services, Audit & Number Sequence Constants
 */

const APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

const APPROVAL_TYPES = {
  ESTIMATE: "ESTIMATE",
  PRODUCT_ORDER: "PRODUCT_ORDER",
  REPRINT: "REPRINT",
  PAST_DATE: "PAST_DATE",
};

const NUMBER_SEQUENCES = {
  JOB_ORDER: "JOB_ORDER",
  SALE_RECEIPT: "SALE_RECEIPT",
  PRODUCT_ORDER: "PRODUCT_ORDER",
  STOCK_TRANSFER: "STOCK_TRANSFER",
  PRODUCTION_ORDER: "PRODUCTION_ORDER",
  DELIVERY_ORDER: "DELIVERY_ORDER",
  EMPLOYEE: "EMPLOYEE",
  INVENTORY_TXN: "INVENTORY_TXN",
};

const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  STATUS_CHANGE: "STATUS_CHANGE",
  STAGE_CHANGE: "STAGE_CHANGE",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  STOCK_MUTATION: "STOCK_MUTATION",
};

module.exports = {
  APPROVAL_STATUS,
  APPROVAL_TYPES,
  NUMBER_SEQUENCES,
  AUDIT_ACTIONS,
};
