/**
 * API 08 - Production Planning, Operations, QC & Delivery Constants
 */

const PRODUCTION_STATUS = {
  PLANNED: "PLANNED",
  IN_PROGRESS: "IN_PROGRESS",
  ON_HOLD: "ON_HOLD",
  QC: "QC",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const OPERATION_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
};

const OPERATION_CODES = {
  PRINT: "PRINT",
  CUTTING: "CUTTING",
  LAMINATION: "LAMINATION",
  BINDING: "BINDING",
  FOLDING: "FOLDING",
  CREASING: "CREASING",
  SPIRAL_BINDING: "SPIRAL_BINDING",
  UV: "UV",
  MOUNTING: "MOUNTING",
  HEAT_PRESS: "HEAT_PRESS",
  PACKING: "PACKING",
};

const QC_RESULTS = {
  PASS: "PASS",
  ISSUE: "ISSUE",
};

const QC_CHECK_TYPES = {
  INITIAL: "INITIAL",
  IN_PROCESS: "IN_PROCESS",
  FINAL: "FINAL",
};

const CORRECTIVE_ACTIONS = {
  NONE: "NONE",
  REWORK: "REWORK",
  REPRINT: "REPRINT",
};

const REPRINT_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  IN_PRODUCTION: "IN_PRODUCTION",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
};

const DELIVERY_STATUS = {
  READY: "READY",
  PACKED: "PACKED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

module.exports = {
  PRODUCTION_STATUS,
  OPERATION_STATUS,
  OPERATION_CODES,
  QC_RESULTS,
  QC_CHECK_TYPES,
  CORRECTIVE_ACTIONS,
  REPRINT_STATUS,
  DELIVERY_STATUS,
};
