/**
 * Job Order Stages and Statuses Constants (Module 06)
 */

const JOB_STAGES = {
  ENQUIRY: "ENQUIRY",
  ESTIMATION: "ESTIMATION",
  ESTIMATE_APPROVAL: "ESTIMATE_APPROVAL",
  DESIGN_QUEUE: "DESIGN_QUEUE",
  DESIGN_ASSIGNED: "DESIGN_ASSIGNED",
  DESIGN_IN_PROGRESS: "DESIGN_IN_PROGRESS",
  SAMPLE_APPROVAL: "SAMPLE_APPROVAL",
  REVISION: "REVISION",
  PRODUCTION_PLANNING: "PRODUCTION_PLANNING",
  PRINTING: "PRINTING",
  FINISHING: "FINISHING",
  PACKING: "PACKING",
  QC: "QC",
  REWORK: "REWORK",
  REPRINT: "REPRINT",
  READY: "READY",
  DELIVERY: "DELIVERY",
  COMPLETED: "COMPLETED",
};

const JOB_STATUSES = {
  DRAFT: "DRAFT",
  ESTIMATION: "ESTIMATION",
  DESIGN: "DESIGN",
  APPROVAL: "APPROVAL",
  PRODUCTION: "PRODUCTION",
  PACKING: "PACKING",
  QC: "QC",
  READY: "READY",
  DELIVERED: "DELIVERED",
  ON_HOLD: "ON_HOLD",
  CANCELLED: "CANCELLED",
};

/**
 * Stage to status mapping (spec 06 §3)
 */
const STAGE_STATUS = {
  [JOB_STAGES.ENQUIRY]: JOB_STATUSES.DRAFT,
  [JOB_STAGES.ESTIMATION]: JOB_STATUSES.ESTIMATION,
  [JOB_STAGES.ESTIMATE_APPROVAL]: JOB_STATUSES.ESTIMATION,
  [JOB_STAGES.DESIGN_QUEUE]: JOB_STATUSES.DESIGN,
  [JOB_STAGES.DESIGN_ASSIGNED]: JOB_STATUSES.DESIGN,
  [JOB_STAGES.DESIGN_IN_PROGRESS]: JOB_STATUSES.DESIGN,
  [JOB_STAGES.SAMPLE_APPROVAL]: JOB_STATUSES.APPROVAL,
  [JOB_STAGES.REVISION]: JOB_STATUSES.DESIGN,
  [JOB_STAGES.PRODUCTION_PLANNING]: JOB_STATUSES.PRODUCTION,
  [JOB_STAGES.PRINTING]: JOB_STATUSES.PRODUCTION,
  [JOB_STAGES.FINISHING]: JOB_STATUSES.PRODUCTION,
  [JOB_STAGES.PACKING]: JOB_STATUSES.PACKING,
  [JOB_STAGES.QC]: JOB_STATUSES.QC,
  [JOB_STAGES.REWORK]: JOB_STATUSES.PRODUCTION,
  [JOB_STAGES.REPRINT]: JOB_STATUSES.PRODUCTION,
  [JOB_STAGES.READY]: JOB_STATUSES.READY,
  [JOB_STAGES.DELIVERY]: JOB_STATUSES.READY,
  [JOB_STAGES.COMPLETED]: JOB_STATUSES.DELIVERED,
};

const PRE_PRODUCTION_STATUSES = [
  JOB_STATUSES.DRAFT,
  JOB_STATUSES.ESTIMATION,
  JOB_STATUSES.DESIGN,
  JOB_STATUSES.APPROVAL,
];

module.exports = {
  JOB_STAGES,
  JOB_STATUSES,
  STAGE_STATUS,
  PRE_PRODUCTION_STATUSES,
};
