/**
 * Job Order Workflow Transitions Table (Module 06 & Module 08)
 */

const { JOB_STAGES } = require("./jobStages");

const TRANSITIONS = {
  [JOB_STAGES.ENQUIRY]: [JOB_STAGES.ESTIMATION],
  [JOB_STAGES.ESTIMATION]: [JOB_STAGES.ESTIMATE_APPROVAL],
  [JOB_STAGES.ESTIMATE_APPROVAL]: [
    JOB_STAGES.DESIGN_QUEUE,
    JOB_STAGES.PRODUCTION_PLANNING,
    JOB_STAGES.ESTIMATION,
  ],
  [JOB_STAGES.DESIGN_QUEUE]: [
    JOB_STAGES.DESIGN_ASSIGNED,
    JOB_STAGES.PRODUCTION_PLANNING, // skip-design
  ],
  [JOB_STAGES.DESIGN_ASSIGNED]: [
    JOB_STAGES.DESIGN_IN_PROGRESS,
    JOB_STAGES.DESIGN_QUEUE,
    JOB_STAGES.PRODUCTION_PLANNING, // skip-design
  ],
  [JOB_STAGES.DESIGN_IN_PROGRESS]: [
    JOB_STAGES.SAMPLE_APPROVAL,
    JOB_STAGES.DESIGN_ASSIGNED, // back to ASSIGNED = reassign
  ],
  [JOB_STAGES.SAMPLE_APPROVAL]: [
    JOB_STAGES.PRODUCTION_PLANNING,
    JOB_STAGES.REVISION,
  ],
  [JOB_STAGES.REVISION]: [
    JOB_STAGES.SAMPLE_APPROVAL,
    JOB_STAGES.DESIGN_ASSIGNED,
  ],
  [JOB_STAGES.PRODUCTION_PLANNING]: [JOB_STAGES.PRINTING],
  [JOB_STAGES.PRINTING]: [
    JOB_STAGES.FINISHING,
    JOB_STAGES.PACKING,
    JOB_STAGES.QC,
  ],
  [JOB_STAGES.FINISHING]: [
    JOB_STAGES.PACKING,
    JOB_STAGES.QC,
  ],
  [JOB_STAGES.PACKING]: [
    JOB_STAGES.QC,
    JOB_STAGES.READY,
  ],
  [JOB_STAGES.QC]: [
    JOB_STAGES.READY,
    JOB_STAGES.REWORK,
    JOB_STAGES.REPRINT,
    JOB_STAGES.PACKING,
  ],
  [JOB_STAGES.REWORK]: [
    JOB_STAGES.PRINTING,
    JOB_STAGES.FINISHING,
    JOB_STAGES.PACKING,
    JOB_STAGES.QC,
  ],
  [JOB_STAGES.REPRINT]: [
    JOB_STAGES.PRINTING,
    JOB_STAGES.FINISHING,
    JOB_STAGES.PACKING,
  ],
  [JOB_STAGES.READY]: [
    JOB_STAGES.DELIVERY,
    JOB_STAGES.COMPLETED,
  ],
  [JOB_STAGES.DELIVERY]: [JOB_STAGES.COMPLETED],
  [JOB_STAGES.COMPLETED]: [],
};

module.exports = {
  TRANSITIONS,
};
