/**
 * Design Workflow Constants (Module 07)
 */

const ASSIGNMENT_TYPES = {
  DESIGNER: "DESIGNER",
  OPERATOR: "OPERATOR",
  QC_INSPECTOR: "QC_INSPECTOR",
};

const ASSIGNMENT_METHODS = {
  ROUND_ROBIN: "ROUND_ROBIN",
  MANUAL: "MANUAL",
  REASSIGN: "REASSIGN",
};

const ASSIGNMENT_STATUSES = {
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  REASSIGNED: "REASSIGNED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const SAMPLE_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REVISION_REQUIRED: "REVISION_REQUIRED",
};

const SAMPLE_DECISIONS = {
  APPROVED: "APPROVED",
  REVISION_REQUIRED: "REVISION_REQUIRED",
};

module.exports = {
  ASSIGNMENT_TYPES,
  ASSIGNMENT_METHODS,
  ASSIGNMENT_STATUSES,
  SAMPLE_STATUSES,
  SAMPLE_DECISIONS,
};
