/**
 * API 03 - Inventory & Ledger Constants
 */

const ITEM_TYPES = {
  RAW_MATERIAL: "RAW_MATERIAL",
  CONSUMABLE: "CONSUMABLE",
  FINISHED_GOOD: "FINISHED_GOOD",
  SERVICE: "SERVICE",
};

const TRANSACTION_TYPES = {
  OPENING: "OPENING",
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  ISSUE: "ISSUE",
  RETURN: "RETURN",
  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",
  JOB_CONSUMPTION: "JOB_CONSUMPTION",
  ADJUSTMENT: "ADJUSTMENT",
};

const STOCK_UNITS = {
  SHEET: "SHEET",
  PCS: "PCS",
  ROLL: "ROLL",
  PACK: "PACK",
  BOX: "BOX",
  KG: "KG",
  METER: "METER",
};

module.exports = {
  ITEM_TYPES,
  TRANSACTION_TYPES,
  STOCK_UNITS,
};
