/**
 * Legacy & Support Modules Swagger (Branches, Categories, Printers, Jumbo Xerox, Payments, Reports, Past Date Requests, Stocks, Total Amounts, Sales)
 */

module.exports = {
  tags: [
    { name: "Branches", description: "Branch profile and store location management" },
    { name: "Categories", description: "Product and job category definitions" },
    { name: "Jumbo Xerox", description: "Wide-format xerox machines, readings, and counters" },
    { name: "Past Date Requests", description: "Workflow approval for retroactive date modifications" },
    { name: "Payments to Collect", description: "Outstanding payment collection and manual receipts" },
    { name: "Printer Readings", description: "Daily meter readings for digital press counters" },
    { name: "Printers", description: "Machinery, production equipment, and digital press master" },
    { name: "Reports & KPIs", description: "Executive KPI summaries and monthly revenue analytics" },
    { name: "Revenue & Total Amounts", description: "Branch daily register closures and revenue settlement" },
    { name: "Sales", description: "Direct retail sales recordings and summaries" },
    { name: "Stocks", description: "Raw material paper stock items and physical reading audits" },
  ],
  schemas: {
    BranchRequest: {
      type: "object",
      required: ["name", "code"],
      properties: {
        name: { type: "string", example: "Koramangala Main Branch" },
        code: { type: "string", example: "BR01" },
        address: { type: "string", example: "123 5th Block, Koramangala, Bengaluru" },
        branchType: { type: "string", enum: ["retail", "warehouse", "corporate"], example: "retail" },
        isActive: { type: "boolean", example: true },
      },
    },
    CategoryRequest: {
      type: "object",
      required: ["categoryId", "categoryName"],
      properties: {
        categoryId: { type: "string", example: "CAT-001" },
        categoryName: { type: "string", example: "Visiting Cards & Stationery" },
      },
    },
    PrinterRequest: {
      type: "object",
      required: ["name", "branchId"],
      properties: {
        name: { type: "string", example: "Konica Minolta C3070" },
        model: { type: "string", example: "AccurioPress C3070" },
        branchId: { $ref: "#/components/schemas/ObjectId" },
        serialNumber: { type: "string", example: "KM-2024-998" },
      },
    },
    PrinterReadingRequest: {
      type: "object",
      required: ["branchId", "printerId", "readingDate", "totalCount"],
      properties: {
        branchId: { $ref: "#/components/schemas/ObjectId" },
        printerId: { $ref: "#/components/schemas/ObjectId" },
        readingDate: { type: "string", format: "date", example: "2026-10-08" },
        totalCount: { type: "number", example: 12450 },
        colorCount: { type: "number", example: 8200 },
        bwCount: { type: "number", example: 4250 },
      },
    },
    JumboXeroxMachineRequest: {
      type: "object",
      required: ["machineName", "branchId"],
      properties: {
        machineName: { type: "string", example: "Xerox Wide-Format 510" },
        model: { type: "string", example: "WF-510" },
        branchId: { $ref: "#/components/schemas/ObjectId" },
        status: { type: "string", enum: ["active", "maintenance", "inactive"], example: "active" },
      },
    },
    JumboXeroxReadingRequest: {
      type: "object",
      required: ["machineId", "readingDate", "startReading", "endReading"],
      properties: {
        machineId: { $ref: "#/components/schemas/ObjectId" },
        readingDate: { type: "string", format: "date", example: "2026-10-08" },
        startReading: { type: "number", example: 1000 },
        endReading: { type: "number", example: 1250 },
        remarks: { type: "string", example: "Architectural blueprint prints" },
      },
    },
    PastDateRequest: {
      type: "object",
      required: ["branchId", "requestDate", "reason"],
      properties: {
        branchId: { $ref: "#/components/schemas/ObjectId" },
        requestDate: { type: "string", format: "date", example: "2026-10-07" },
        reason: { type: "string", example: "System maintenance downtime correction" },
      },
    },
    PaymentRequest: {
      type: "object",
      required: ["amount", "paymentMode"],
      properties: {
        customerId: { $ref: "#/components/schemas/ObjectId", nullable: true },
        amount: { type: "number", example: 2500.0 },
        paymentMode: { $ref: "#/components/schemas/PaymentModeEnum" },
        transactionReference: { type: "string", example: "UPI-202610-9988" },
        notes: { type: "string", example: "Advance payment for bulk brochure order" },
      },
    },
    TotalAmountRequest: {
      type: "object",
      required: ["branchId", "date", "cashAmount", "onlineAmount"],
      properties: {
        branchId: { $ref: "#/components/schemas/ObjectId" },
        date: { type: "string", format: "date", example: "2026-10-08" },
        cashAmount: { type: "number", example: 15400.0 },
        onlineAmount: { type: "number", example: 28600.0 },
        totalAmount: { type: "number", example: 44000.0 },
      },
    },
    StockItemRequest: {
      type: "object",
      required: ["itemName", "unit"],
      properties: {
        itemName: { type: "string", example: "Gloss Paper Roll 36 Inch" },
        category: { type: "string", example: "Paper Rolls" },
        unit: { type: "string", example: "ROLL" },
        minStockLevel: { type: "number", example: 5 },
        currentStock: { type: "number", example: 20 },
      },
    },
    StockReadingRequest: {
      type: "object",
      required: ["itemId", "branchId", "recordedCount"],
      properties: {
        itemId: { $ref: "#/components/schemas/ObjectId" },
        branchId: { $ref: "#/components/schemas/ObjectId" },
        recordedCount: { type: "number", example: 18 },
        recordedDate: { type: "string", format: "date", example: "2026-10-08" },
      },
    },
    SaleRequest: {
      type: "object",
      required: ["customerName", "amount"],
      properties: {
        customerName: { type: "string", example: "Priya Enterprises" },
        amount: { type: "number", example: 1850.0 },
        description: { type: "string", example: "Brochure and banner printing" },
      },
    },
  },
  paths: {
    "/branches": {
      get: {
        tags: ["Branches"],
        summary: "List Branches",
        description: "Returns all company branches and operational facilities.",
        operationId: "getBranches",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of branches", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Branches"],
        summary: "Create Branch",
        description: "Registers a new branch location.",
        operationId: "createBranch",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/BranchRequest" } } },
        },
        responses: { 201: { description: "Branch created", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/branches/{id}": {
      get: {
        tags: ["Branches"],
        summary: "Get Branch by ID",
        description: "Retrieves details of a branch.",
        operationId: "getBranchById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Branch details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Branches"],
        summary: "Update Branch",
        description: "Replaces branch configuration details.",
        operationId: "updateBranch",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/BranchRequest" } } },
        },
        responses: { 200: { description: "Branch updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      patch: {
        tags: ["Branches"],
        summary: "Patch Branch",
        description: "Partially updates branch details.",
        operationId: "patchBranch",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Branch updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Branches"],
        summary: "Delete Branch",
        description: "Deactivates or deletes branch.",
        operationId: "deleteBranch",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Branch deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/general/categories": {
      get: {
        tags: ["Categories"],
        summary: "List Categories",
        description: "Returns master job and product categories.",
        operationId: "getCategories",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of categories", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Categories"],
        summary: "Create Category",
        description: "Creates a new category.",
        operationId: "createCategory",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/CategoryRequest" } } },
        },
        responses: { 201: { description: "Category created", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/general/finalized-dates": {
      get: {
        tags: ["Categories"],
        summary: "List Finalized Dates",
        description: "Returns locked daily accounting dates per branch.",
        operationId: "getFinalizedDates",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Finalized dates list", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Categories"],
        summary: "Set Finalized Date",
        description: "Locks accounting registers for the selected date.",
        operationId: "setFinalizedDate",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  branchId: { $ref: "#/components/schemas/ObjectId" },
                  finalizedDate: { type: "string", format: "date", example: "2026-10-08" },
                },
              },
            },
          },
        },
        responses: { 201: { description: "Date finalized", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/general/inventory-movements": {
      get: {
        tags: ["Categories"],
        summary: "List Inventory Movements",
        description: "Returns raw material movement records.",
        operationId: "getGeneralInventoryMovements",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of inventory movements", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Categories"],
        summary: "Create Inventory Movement",
        description: "Records stock movement event.",
        operationId: "createGeneralInventoryMovement",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { type: "object", properties: { itemId: { $ref: "#/components/schemas/ObjectId" }, quantity: { type: "number" }, type: { type: "string" } } } } },
        },
        responses: { 201: { description: "Inventory movement created", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/general/sales": {
      get: {
        tags: ["Sales"],
        summary: "List General Sales",
        description: "Returns direct retail sales records.",
        operationId: "getSales",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Sales records", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Sales"],
        summary: "Create General Sale",
        description: "Records a retail point-of-sale transaction.",
        operationId: "createSale",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/SaleRequest" } } },
        },
        responses: { 201: { description: "Sale recorded", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/general/sales/{id}": {
      get: {
        tags: ["Sales"],
        summary: "Get General Sale by ID",
        description: "Retrieves details of a single sale.",
        operationId: "getSaleById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Sale details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/printers": {
      get: {
        tags: ["Printers"],
        summary: "List Printers",
        description: "Returns all printing machines and digital presses.",
        operationId: "getPrinters",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of printers", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Printers"],
        summary: "Create Printer",
        description: "Registers a new printer machine.",
        operationId: "createPrinter",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PrinterRequest" } } },
        },
        responses: { 201: { description: "Printer registered", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/printers/{id}": {
      get: {
        tags: ["Printers"],
        summary: "Get Printer by ID",
        description: "Retrieves details of a printer.",
        operationId: "getPrinterById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Printer details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Printers"],
        summary: "Update Printer",
        description: "Updates printer machine details.",
        operationId: "updatePrinter",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PrinterRequest" } } },
        },
        responses: { 200: { description: "Printer updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Printers"],
        summary: "Delete Printer",
        description: "Removes or decommissions a printer machine.",
        operationId: "deletePrinter",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Printer deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/printer-readings": {
      get: {
        tags: ["Printer Readings"],
        summary: "List Printer Readings",
        description: "Returns meter readings for digital press counters.",
        operationId: "getPrinterReadings",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Printer meter readings", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Printer Readings"],
        summary: "Record Printer Reading",
        description: "Records daily meter count for color and black & white prints.",
        operationId: "createPrinterReading",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PrinterReadingRequest" } } },
        },
        responses: { 201: { description: "Printer reading recorded", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/printer-readings/{id}": {
      get: {
        tags: ["Printer Readings"],
        summary: "Get Printer Reading by ID",
        description: "Retrieves a specific printer reading log.",
        operationId: "getPrinterReadingById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Printer reading details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Printer Readings"],
        summary: "Update Printer Reading",
        description: "Updates meter reading values.",
        operationId: "updatePrinterReading",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PrinterReadingRequest" } } },
        },
        responses: { 200: { description: "Printer reading updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Printer Readings"],
        summary: "Delete Printer Reading",
        description: "Deletes a meter reading entry.",
        operationId: "deletePrinterReading",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Printer reading deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/machines": {
      get: {
        tags: ["Jumbo Xerox"],
        summary: "List Jumbo Xerox Machines",
        description: "Returns wide-format photocopy and scanning equipment.",
        operationId: "getJumboXeroxMachines",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of machines", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Jumbo Xerox"],
        summary: "Create Jumbo Xerox Machine",
        description: "Registers a new wide-format xerox machine.",
        operationId: "createJumboXeroxMachine",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/JumboXeroxMachineRequest" } } },
        },
        responses: { 201: { description: "Machine registered", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/machines/{id}": {
      get: {
        tags: ["Jumbo Xerox"],
        summary: "Get Jumbo Xerox Machine by ID",
        description: "Retrieves details of a machine.",
        operationId: "getJumboXeroxMachineById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Machine details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Jumbo Xerox"],
        summary: "Update Jumbo Xerox Machine",
        description: "Updates machine configuration.",
        operationId: "updateJumboXeroxMachine",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/JumboXeroxMachineRequest" } } },
        },
        responses: { 200: { description: "Machine updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Jumbo Xerox"],
        summary: "Delete Jumbo Xerox Machine",
        description: "Decommissions a machine.",
        operationId: "deleteJumboXeroxMachine",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Machine deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/configurations": {
      get: {
        tags: ["Jumbo Xerox"],
        summary: "List Jumbo Xerox Configurations",
        description: "Returns configuration options for jumbo xerox equipment.",
        operationId: "getJumboXeroxConfigurations",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Configurations list", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Jumbo Xerox"],
        summary: "Create Jumbo Xerox Configuration",
        description: "Saves a new jumbo xerox equipment configuration.",
        operationId: "createJumboXeroxConfiguration",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/JumboXeroxMachineRequest" } } },
        },
        responses: { 201: { description: "Configuration saved", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/configurations/{id}": {
      get: {
        tags: ["Jumbo Xerox"],
        summary: "Get Jumbo Xerox Configuration by ID",
        description: "Retrieves a specific configuration.",
        operationId: "getJumboXeroxConfigurationById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Configuration details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Jumbo Xerox"],
        summary: "Update Jumbo Xerox Configuration",
        description: "Updates configuration parameters.",
        operationId: "updateJumboXeroxConfiguration",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/JumboXeroxMachineRequest" } } },
        },
        responses: { 200: { description: "Configuration updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Jumbo Xerox"],
        summary: "Delete Jumbo Xerox Configuration",
        description: "Deletes configuration.",
        operationId: "deleteJumboXeroxConfiguration",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Configuration deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/readings": {
      get: {
        tags: ["Jumbo Xerox"],
        summary: "List Jumbo Xerox Readings",
        description: "Returns square meter/linear meter reading records.",
        operationId: "getJumboXeroxReadings",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Readings list", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Jumbo Xerox"],
        summary: "Record Jumbo Xerox Reading",
        description: "Records start and end meter counts.",
        operationId: "createJumboXeroxReading",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/JumboXeroxReadingRequest" } } },
        },
        responses: { 201: { description: "Reading recorded", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/jumbo-xerox/readings/{id}": {
      delete: {
        tags: ["Jumbo Xerox"],
        summary: "Delete Jumbo Xerox Reading",
        description: "Deletes a reading entry.",
        operationId: "deleteJumboXeroxReading",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Reading deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/past-date-requests": {
      get: {
        tags: ["Past Date Requests"],
        summary: "List Past Date Requests",
        description: "Returns requests to record or modify entries on past dates.",
        operationId: "getPastDateRequests",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Requests list", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Past Date Requests"],
        summary: "Create Past Date Request",
        description: "Submits request for admin approval to perform retroactive transactions.",
        operationId: "createPastDateRequest",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PastDateRequest" } } },
        },
        responses: { 201: { description: "Request submitted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/past-date-requests/{id}": {
      get: {
        tags: ["Past Date Requests"],
        summary: "Get Past Date Request by ID",
        description: "Retrieves request details.",
        operationId: "getPastDateRequestById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Request details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Past Date Requests"],
        summary: "Update Past Date Request",
        description: "Modifies past date request.",
        operationId: "updatePastDateRequest",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PastDateRequest" } } },
        },
        responses: { 200: { description: "Request updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Past Date Requests"],
        summary: "Delete Past Date Request",
        description: "Cancels past date request.",
        operationId: "deletePastDateRequest",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Request deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/payments": {
      get: {
        tags: ["Payments to Collect"],
        summary: "List Payments",
        description: "Returns payment transactions and receipts.",
        operationId: "getPayments",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of payments", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Payments to Collect"],
        summary: "Create Payment",
        description: "Records a customer payment receipt.",
        operationId: "createPayment",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PaymentRequest" } } },
        },
        responses: { 201: { description: "Payment recorded", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/payments/{id}": {
      get: {
        tags: ["Payments to Collect"],
        summary: "Get Payment by ID",
        description: "Retrieves details of a payment.",
        operationId: "getPaymentById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Payment details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Payments to Collect"],
        summary: "Update Payment",
        description: "Updates payment details.",
        operationId: "updatePayment",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/PaymentRequest" } } },
        },
        responses: { 200: { description: "Payment updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Payments to Collect"],
        summary: "Delete Payment",
        description: "Deletes a payment entry.",
        operationId: "deletePayment",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Payment deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/reports/dashboard-summary": {
      get: {
        tags: ["Reports & KPIs"],
        summary: "Get Dashboard Summary Report",
        description: "Returns aggregated KPI metrics including revenue, orders, active jobs, and collections.",
        operationId: "getReportsDashboardSummary",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Dashboard summary KPIs", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/reports/monthly-revenue": {
      get: {
        tags: ["Reports & KPIs"],
        summary: "Get Monthly Revenue Report",
        description: "Returns monthly sales and cash/online collection analytics.",
        operationId: "getReportsMonthlyRevenue",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Monthly revenue report", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/total-amounts": {
      get: {
        tags: ["Revenue & Total Amounts"],
        summary: "List Total Amounts",
        description: "Returns daily register reconciliation entries.",
        operationId: "getTotalAmounts",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Daily register settlements", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Revenue & Total Amounts"],
        summary: "Create Total Amount Record",
        description: "Records end-of-day register closure.",
        operationId: "createTotalAmount",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/TotalAmountRequest" } } },
        },
        responses: { 201: { description: "Daily closure saved", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/total-amounts/{id}": {
      get: {
        tags: ["Revenue & Total Amounts"],
        summary: "Get Total Amount Record by ID",
        description: "Retrieves a single register closure record.",
        operationId: "getTotalAmountById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Closure details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Revenue & Total Amounts"],
        summary: "Update Total Amount Record",
        description: "Updates register reconciliation values.",
        operationId: "updateTotalAmount",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/TotalAmountRequest" } } },
        },
        responses: { 200: { description: "Closure updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Revenue & Total Amounts"],
        summary: "Delete Total Amount Record",
        description: "Deletes a closure entry.",
        operationId: "deleteTotalAmount",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Closure deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/stocks/items": {
      get: {
        tags: ["Stocks"],
        summary: "List Stock Items",
        description: "Returns paper, media, and lamination inventory items.",
        operationId: "getStockItems",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "List of stock items", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Stocks"],
        summary: "Create Stock Item",
        description: "Creates a new stock raw material master item.",
        operationId: "createStockItem",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/StockItemRequest" } } },
        },
        responses: { 201: { description: "Stock item created", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/stocks/items/{id}": {
      get: {
        tags: ["Stocks"],
        summary: "Get Stock Item by ID",
        description: "Retrieves details of a stock item.",
        operationId: "getStockItemById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Stock item details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Stocks"],
        summary: "Update Stock Item",
        description: "Updates stock item properties.",
        operationId: "updateStockItem",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/StockItemRequest" } } },
        },
        responses: { 200: { description: "Stock item updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Stocks"],
        summary: "Delete Stock Item",
        description: "Deletes a stock item.",
        operationId: "deleteStockItem",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Stock item deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/stocks/readings": {
      get: {
        tags: ["Stocks"],
        summary: "List Stock Readings",
        description: "Returns physical stock audit counts.",
        operationId: "getStockReadings",
        security: [{ bearerAuth: [] }],
        responses: { 200: { description: "Stock readings list", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      post: {
        tags: ["Stocks"],
        summary: "Record Stock Reading",
        description: "Submits physical inventory recount audit.",
        operationId: "createStockReading",
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/StockReadingRequest" } } },
        },
        responses: { 201: { description: "Stock reading recorded", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
    "/stocks/readings/{id}": {
      get: {
        tags: ["Stocks"],
        summary: "Get Stock Reading by ID",
        description: "Retrieves a specific stock reading.",
        operationId: "getStockReadingById",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Stock reading details", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      put: {
        tags: ["Stocks"],
        summary: "Update Stock Reading",
        description: "Updates stock reading count.",
        operationId: "updateStockReading",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/StockReadingRequest" } } },
        },
        responses: { 200: { description: "Stock reading updated", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
      delete: {
        tags: ["Stocks"],
        summary: "Delete Stock Reading",
        description: "Deletes a stock reading audit entry.",
        operationId: "deleteStockReading",
        security: [{ bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/ObjectId" } }],
        responses: { 200: { description: "Stock reading deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiSuccessResponse" } } } } },
      },
    },
  },
};
